### ISSUE TITLE
Minor errors in IS Benchmark

### ISSUE THREAD

**Issue by Armassarion** [dalvangriebler/NPB-CPP#1]
1. The "setparams.cpp" file doesn't generate any value for the IS benchmark.
This is because the "case IS" (line 670 of setparams.cpp) is bellow the "case CG".

2. The "is.cpp" file doesn't use "c_print_results" (line 916) like the other benchmark does : it exepects constant such as "CC", "CLINK", ... while "setparams" generate "CS1", "CS2", ...

A fix is available in attached files.

Sincerely,
Ksander Ejjaaouani.
[is_fix.zip](https://github.com/dalvangriebler/NPB-CPP/files/1813665/is_fix.zip)

**Comment by dalvangriebler** [comment]
Thank you, we solved these minor errors. :)
