### ISSUE TITLE
Wrong initialization of MG ? 

### ISSUE THREAD

**Issue by Armassarion** [dalvangriebler/NPB-CPP#2]
https://github.com/dalvangriebler/NPB-CPP/blob/d6479ae08633d417ed9ae9edf6ce0535dad2ad65/NPB-SER/MG/mg.cpp#L330-L331
I think it is a bug: m2 is equal to nz and m3 to ny instead of the reverse.

**Comment by dalvangriebler** [comment]
Thanks, bug fixed
